// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWfdvYw395MUYw9PLJj-R79Vh3G8i4-RI',
    appId: '1:156005404177:web:4a48a5529d6d872d626bb0',
    messagingSenderId: '156005404177',
    projectId: 'department-73331',
    authDomain: 'department-73331.firebaseapp.com',
    databaseURL: 'https://department-73331-default-rtdb.firebaseio.com',
    storageBucket: 'department-73331.firebasestorage.app',
    measurementId: 'G-XKXMYW1DM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmQ2xOcaW1uLAOw_MTYVu8b1ZW3LocXXg',
    appId: '1:156005404177:android:f9b04ecd7097791b626bb0',
    messagingSenderId: '156005404177',
    projectId: 'department-73331',
    databaseURL: 'https://department-73331-default-rtdb.firebaseio.com',
    storageBucket: 'department-73331.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD26ROwdARpaTmDqUj9SRBuA-gFJ3hH_Ns',
    appId: '1:156005404177:ios:e02194871ed66a2e626bb0',
    messagingSenderId: '156005404177',
    projectId: 'department-73331',
    databaseURL: 'https://department-73331-default-rtdb.firebaseio.com',
    storageBucket: 'department-73331.firebasestorage.app',
    iosBundleId: 'com.example.educationalTimetableApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD26ROwdARpaTmDqUj9SRBuA-gFJ3hH_Ns',
    appId: '1:156005404177:ios:e02194871ed66a2e626bb0',
    messagingSenderId: '156005404177',
    projectId: 'department-73331',
    databaseURL: 'https://department-73331-default-rtdb.firebaseio.com',
    storageBucket: 'department-73331.firebasestorage.app',
    iosBundleId: 'com.example.educationalTimetableApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWfdvYw395MUYw9PLJj-R79Vh3G8i4-RI',
    appId: '1:156005404177:web:31b572ab39805ff7626bb0',
    messagingSenderId: '156005404177',
    projectId: 'department-73331',
    authDomain: 'department-73331.firebaseapp.com',
    databaseURL: 'https://department-73331-default-rtdb.firebaseio.com',
    storageBucket: 'department-73331.firebasestorage.app',
    measurementId: 'G-PQRL100GKJ',
  );
}
